# Generated by Django 3.1.7 on 2021-09-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210920_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(default=False, verbose_name='正文markdown吾法'),
        ),
    ]
