# Generated by Django 3.1.7 on 2021-04-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20210406_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
